-- MySQL Script generated by MySQL Workbench
-- Model: Sistema Biblioteca

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE;

SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,
NO_ZERO_IN_DATE,NO_ZERO_DATE,
ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- CREAR BASE DE DATOS
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8;
USE `mydb`;

-- -----------------------------------------------------
-- TABLA ROLES
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `Roles` (

  `id_roles` INT NOT NULL AUTO_INCREMENT,

  `nombre_rol` VARCHAR(50) NOT NULL,
  `descripcion_rol` VARCHAR(200) NULL,

  `fecha_creacion` DATETIME NOT NULL,
  `fecha_modificacion` DATETIME NULL,
  `estado` BOOLEAN NOT NULL,

  PRIMARY KEY (`id_roles`)

)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- TABLA USUARIOS
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `Usuarios` (

  `id_usuario` INT NOT NULL AUTO_INCREMENT,

  `nombre_usuario` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,

  `fecha_creacion` DATETIME NOT NULL,
  `fecha_modificacion` DATETIME NULL,
  `estado` BOOLEAN NOT NULL,

  `id_roles` INT NOT NULL,

  PRIMARY KEY (`id_usuario`),

  INDEX `fk_Usuarios_Roles1_idx` (`id_roles` ASC) VISIBLE,

  CONSTRAINT `fk_Usuarios_Roles1`
    FOREIGN KEY (`id_roles`)
    REFERENCES `Roles` (`id_roles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION

)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- TABLA AUTORES
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `Autores` (

  `id_autor` INT NOT NULL AUTO_INCREMENT,

  `nombre_autor` VARCHAR(50) NOT NULL,
  `apellido_autor` VARCHAR(50) NOT NULL,
  `nacionalidad_autor` VARCHAR(100) NOT NULL,
  `email_autor` VARCHAR(150) NOT NULL,

  `fecha_creacion` DATETIME NOT NULL,
  `fecha_modificacion` DATETIME NULL,
  `estado` BOOLEAN NOT NULL,

  PRIMARY KEY (`id_autor`)

)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- TABLA LIBROS
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `Libros` (

  `id_libro` INT NOT NULL AUTO_INCREMENT,

  `titulo_libro` VARCHAR(100) NOT NULL,
  `fecha_publicacion` DATE NOT NULL,
  `descripcion_libro` VARCHAR(200) NOT NULL,

  `fecha_creacion` DATETIME NOT NULL,
  `fecha_modificacion` DATETIME NULL,
  `estado` BOOLEAN NOT NULL,

  `id_autor` INT NOT NULL,

  PRIMARY KEY (`id_libro`),

  INDEX `fk_Libros_Autores1_idx` (`id_autor` ASC) VISIBLE,

  CONSTRAINT `fk_Libros_Autores1`
    FOREIGN KEY (`id_autor`)
    REFERENCES `Autores` (`id_autor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION

)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- TABLA PRESTAMO
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `Prestamo` (

  `id_prestamo` INT NOT NULL AUTO_INCREMENT,

  `fecha_prestamo` DATE NOT NULL,
  `fecha_devolucion` DATE NULL,

  `fecha_creacion` DATETIME NOT NULL,
  `fecha_modificacion` DATETIME NULL,
  `estado` BOOLEAN NOT NULL,

  `id_usuario` INT NOT NULL,
  `id_libro` INT NOT NULL,

  PRIMARY KEY (`id_prestamo`),

  INDEX `fk_Prestamo_Usuarios_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_Prestamo_Libros1_idx` (`id_libro` ASC) VISIBLE,

  CONSTRAINT `fk_Prestamo_Usuarios`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `Usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

  CONSTRAINT `fk_Prestamo_Libros1`
    FOREIGN KEY (`id_libro`)
    REFERENCES `Libros` (`id_libro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION

)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- INSERTAR DATOS EN ROLES
-- -----------------------------------------------------

INSERT INTO Roles
(nombre_rol, descripcion_rol, fecha_creacion, estado)

VALUES

("Administrador", "Control total del sistema", NOW(), TRUE),

("Bibliotecario", "Gestiona libros y prestamos", NOW(), TRUE),

("Usuario", "Usuario normal del sistema", NOW(), TRUE);

SELECT * FROM Roles;

-- -----------------------------------------------------
-- INSERTAR DATOS EN USUARIOS
-- -----------------------------------------------------

INSERT INTO Usuarios
(nombre_usuario, email, password, id_roles,
fecha_creacion, estado)

VALUES

("marcelo", "marcelo@gmail.com", "randy123", 2,
NOW(), TRUE),

("yoycer", "yoycer@gmail.com", "akon123", 1,
NOW(), TRUE),

("fabrizio", "fabrizio@gmail.com", "tete123", 2,
NOW(), TRUE),

("seba", "seba@gmail.com", "anne123", 3,
NOW(), TRUE);

SELECT * FROM Usuarios;

-- -----------------------------------------------------
-- INSERTAR DATOS EN AUTORES
-- -----------------------------------------------------

INSERT INTO Autores
(nombre_autor, apellido_autor,
nacionalidad_autor, email_autor,
fecha_creacion, estado)

VALUES

("Yoycer", "Garcia",
"Venezolano", "yoycer@gmail.com",
NOW(), TRUE),

("Fabrizio", "Ortiz",
"Boliviano", "fabrizio@gmail.com",
NOW(), TRUE),

("Marcelo", "Rios",
"Chileno", "marcelo@gmail.com",
NOW(), TRUE);

SELECT * FROM Autores;

-- -----------------------------------------------------
-- INSERTAR DATOS EN LIBROS
-- -----------------------------------------------------

INSERT INTO Libros
(titulo_libro, descripcion_libro,
fecha_publicacion, id_autor,
fecha_creacion, estado)

VALUES

("Un dia sin ti",
"Novela de la calle",
"2026-05-25", 1,
NOW(), TRUE),

("Flor que crece",
"Evitar la casa",
"2026-05-25", 2,
NOW(), TRUE),

("Otro dia mas",
"Sufrimiento y amor",
"2026-05-25", 3,
NOW(), TRUE);

SELECT * FROM Libros;

-- -----------------------------------------------------
-- INSERTAR DATOS EN PRESTAMOS
-- -----------------------------------------------------

INSERT INTO Prestamo
(fecha_prestamo, fecha_devolucion,
id_usuario, id_libro,
fecha_creacion, estado)

VALUES

("2026-05-25", "2026-06-01",
1, 1,
NOW(), TRUE),

("2026-05-26", "2026-06-03",
2, 2,
NOW(), TRUE),

("2026-05-27", "2026-06-05",
4, 3,
NOW(), TRUE);

SELECT * FROM Prestamo;

-- -----------------------------------------------------
-- RESTAURAR CONFIGURACIONES
-- -----------------------------------------------------

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;