-- MySQL Script generated by MySQL Workbench
-- Tue May 19 12:17:35 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistema_mensajes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema_mensajes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema_mensajes` DEFAULT CHARACTER SET utf8 ;
USE `sistema_mensajes` ;

-- -----------------------------------------------------
-- Table `sistema_mensajes`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_mensajes`.`roles` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre_rol` VARCHAR(50) NOT NULL,
  `descripcion_rol` VARCHAR(300) NOT NULL,
  `created_at` DATETIME NULL CURRENT_TIMESTAMP, --CURRENT_TIMESTAMP: Valor fecha y hora
  `update_at` DATETIME NULL CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  `delete` TINYINT(1) DEFAULT 0,
  -- Borrado lógico - No se borra el registro fisicamente
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;

-- DIEGO MUERE - DEBEMOS SACARLO DEL SISTEMA, BORRADO FISICO DELETE FROM USUARIO
-- CON DELETE EL DATO DEJA DE EXISTIR - NO SE PUEDE RECUPERAR
-- EN CAMBIO CON BORRADO LÓGICO (campo deleted activo - deleted (1))
-- PODEMOS OCULTAR EL USUARIO PARA QUE EL CLIENTE NO LO VEA
-- PERO NO SALE DEL SISTEMA

-- -----------------------------------------------------
-- Table `sistema_mensajes`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_mensajes`.`usuarios` (
  `id_usuarios` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `email` VARCHAR(140) NOT NULL,
  `password_hash` VARCHAR(200) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `created_by` INT NULL,
  `delete` TINYINT(1) NULL,
  `id_rol` INT NOT NULL,
  PRIMARY KEY (`id_usuarios`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `password_hash_UNIQUE` (`password_hash` ASC) VISIBLE,
  INDEX `fk_usuarios_roles_idx` (`id_rol` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_roles`
    FOREIGN KEY (`id_rol`)
    REFERENCES `sistema_mensajes`.`roles` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_mensajes`.`mensajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_mensajes`.`mensajes` (
  `id_mensajes` INT NOT NULL AUTO_INCREMENT,
  `contenido` TEXT NOT NULL,
  `created_at` DATETIME NULL,
  `update_at` DATETIME NULL,
  `created_by` INT NULL,
  `delete` TINYINT(1) NULL,
  `emisor` INT NOT NULL,
  `usuarios_id_usuarios1` INT NOT NULL,
  PRIMARY KEY (`id_mensajes`),
  INDEX `fk_mensajes_usuarios1_idx` (`emisor` ASC) VISIBLE,
  INDEX `fk_mensajes_usuarios2_idx` (`usuarios_id_usuarios1` ASC) VISIBLE,
  CONSTRAINT `fk_mensajes_usuarios1`
    FOREIGN KEY (`emisor`)
    REFERENCES `sistema_mensajes`.`usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mensajes_usuarios2`
    FOREIGN KEY (`usuarios_id_usuarios1`)
    REFERENCES `sistema_mensajes`.`usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_mensajes`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_mensajes`.`comentarios` (
  `id_comentario` INT NOT NULL AUTO_INCREMENT,
  `contenido` TEXT NOT NULL,
  `created_at` DATETIME NULL,
  `update_at` DATETIME NULL,
  `created_by` INT NULL,
  `delete` TINYINT(1) NULL,
  `id_usuarios` INT NOT NULL,
  PRIMARY KEY (`id_comentario`),
  INDEX `fk_comentarios_usuarios1_idx` (`id_usuarios` ASC) VISIBLE,
  CONSTRAINT `fk_comentarios_usuarios1`
    FOREIGN KEY (`id_usuarios`)
    REFERENCES `sistema_mensajes`.`usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

---Insertar datos en tablas

USE sistema_mensajes;
INSERT INTO roles(nombre_rol, descripcion_rol)
VALUES("admin", "Control total"),
("usuario comun", "Sin permisos"),
("Invitado", "usuario temporal con permisos limitados");
INSERT INTO usuarios(nombre_usuario, password_hash, email, id_rol) 
VALUES ("randy123", "randy123", "randy@gmail.com", 2),
("akon123", "akon123", "akon@gmail.com", 1),
("tete", "tete", "tete@gmail.com", 3),
("anne", "anne", "anne@gmail.com", 3),
("martin", "martin", "martin@gmail.com", 3);
SELECT * FROM roles;
SELECT * FROM usuarios;
INSERT INTO comentarios(contenido, created_by, id_usuario)
VALUES("Hola este es un comentario",1 ,1),
("Hola soy el akon admin",1 ,1),
("Hola soy tete", 3, 3);
SELECT * FROM comentarios;

INSERT INTO mensajes(contenido,created_by,emisor, receptor)
VALUES ("Hola Martin, eres el mejor",1 ,1 , 5),
("Hola tete, ¿hiciste la tarea?", 4 , 4, 3),
("Hola Randy, mañana es feriado",3, 3, 1);

SELECT * FROM mensajes;
-- CONSULTAS SIMPLES CON CONDICIÓN
-- WHERE EN MYSQL
-- MOSTRAR MENSAJES DONDE EL REMITENTE SEA RANDY
SELECT contenido, emisor
FROM mensajes 
WHERE emisor = 1; -- WHERE aplica condición sobre consulta

-- MOSTRAR USUARIOS QUE ESTAN ACTIVOS (DELETED 0)
SELECT nombre_usuario, email, id_rol, deleted
FROM usuarios
WHERE deleted = 0;
-- MOSTRAR USUARIOS QUE ESTAN ELIMINADO (DELETED 1)
SELECT nombre_usuario, email, id_rol, deleted
FROM usuarios
WHERE deleted = 1;

-- BORRAR UN USUARIO (BORRADO LOGICO)
UPDATE usuarios
SET deleted = 1
WHERE id_usuario = 1;

-- BORRAR UN USUARIO 
UPDATE usuarios
SET deleted = 0
WHERE id_usuario = 1;

-- TAREA 
-- MOSTRAR ROLES DE USUARIO
SELECT nombre_rol, descripcion_rol
FROM roles
WHERE deleted = 0;
-- ELIMINAR 2 ROLES DE USUARIO
UPDATE roles 
SET deleted = 1
WHERE id_rol = 2;


UPDATE roles
SET deleted = 1
WHERE id_rol = 3;
-- RECUPERAR 1 ROL DE USUARIO
UPDATE roles
SET deleted = 0
WHERE id_rol = 3;